[general]
live_config_reload = true
working_directory = "None"

[terminal]
shell = { program = "zsh", args = ["-l", "-c", "tmux attach || tmux"] }

[window]
title = "Alacritty"
dynamic_title = true

decorations = "none"

opacity = 1

padding.x = 15
padding.y = 15

[window.dimensions]
columns = 160
lines = 80

[cursor.style]
shape= "Block"
blinking = "Never"

[colors]
#transparent_background_colors = true
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
normal.family = "JetBrainsMonoNL Nerd Font Mono"
normal.style = "Regular"
size = 12.0

[font.bold]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Bold Italic"

[colors.primary]
background = "#0C0C12"
foreground = "#a5b6cf"

[colors.normal]
black = "#1c1e27"
blue = "#8baff1"
cyan = "#98d3ee"
green = "#95d3af"
magenta = "#c79bf0"
red = "#e26c7c"
white = "#d0d3d8"
yellow = "#f1d8a5"

[colors.bright]
black = "#323947"
blue = "#86aaec"
cyan = "#93cee9"
green = "#90ceaa"
magenta = "#c296eb"
red = "#dd6777"
white = "#cbced3"
yellow = "#ecd3a0"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.selection]
text = "CellForeground"
background = "0x303340"

[colors.vi_mode_cursor]
text = "CellBackground"
cursor = "CellForeground"